[package]
name = "ZubrDSP"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "playback_prototyping"
path = "prototypes/audio_playback.rs"

[[bin]]
name = "plotting_prototyping"
path = "prototypes/plotting.rs"

[[bin]]
name = "tui_prototyping"
path = "prototypes/frontend.rs"

[dependencies]
async-std = "1.13.0"
futures = "0.3.31"
num = "0.4.3"
rand = "0.9.1"
crossbeam = "0.8"
rayon = "1.8"
atomic_enum = "0.3.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
strum = "0.26.3"
rusb = "0.9.4"
rustfft = "6"
symphonia = "0.5.4"
awedio = "0.5.0"
rodio = "0.21.1"
crossbeam-queue = "0.3.12"
env_logger = "0.11.8"
log = "0.4.27"
num_enum = "0.7.4"
thread-priority = "2.1.0"
plotters = "0.3.7"
systemstat = "0.2.5"
piston_window = "0.132.0"
plotters-piston = "0.3.0"
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
directories = "6.0.0"
lazy_static = "1.5.0"
itertools = "0.14.0"
unicode-width = "0.2.1"
tui-logger = "0.17.3"
tui-big-text = "0.7.1"
tui-menu = "0.3.0"
tui-nodes = "0.9.0"
tui-tree-widget = "0.23.1"
