// pub mod pipeline_struct;
// pub mod welder;
// pub mod node_enum;
pub mod pipeline;
pub mod pipeline_step;
pub mod pipeline_thread;
pub mod tests;
mod endpoints;
mod sources;
pub mod valid_types;
pub mod pipeline_traits;
mod pipeline_results;
mod pipeline_comms;
//mod dummy;
//mod curses;